Accept regexps and arrays in allow_origin option
jdesrosiers/sinatra-cors pull request #4
Opened 2020-06-30 15:57 UTC by frm

I'm not sure you want to include this but I just had to add support for regexps and lists in a project using this gem.

The use case was due to pull requests being deployed each in a different Netlify URL and those being different from production. My solution was to implement this and set `allow_origin` to `[/deploy-preview.*--myapp.netlify.app/, "https://production.my.app"]`.

2020-07-01 13:22 UTC, jdesrosiers commented
This sounds like a great addition. Thanks! I'll review as soon as I can, but it probably won't be til the weekend.

2020-07-11 18:03 UTC, jdesrosiers requested changes
Sorry for the delay. This looks good. There's just a small typo in a test description. Also, would you mind updating the README to reflect the changes?

2020-07-11 18:03 UTC, jdesrosiers commented on spec/cors_spec.rb
> +    it "should allow regexps on the :allowed_origin option" do
The config should be `:allow_origin` not `:allowed_origin`. Same on line160.

2020-07-16 16:48 UTC, frm commented
Sorry it took me so long, just updated 👍

2020-07-26 20:41 UTC, merged

2020-07-26 22:53 UTC, jdesrosiers commented
Thanks! New version has been deployed as v1.2.0